on:
  push:
  schedule:
    - cron: '*/5 * * * *' # will run every 5 minutes

jobs:
  job0:
    runs-on: ubuntu-latest
    steps:
      - name: visit https://calclocation.applinzi.com
        run: curl "https://calclocation.applinzi.com/isdbconnect.php"
